/**
 * Gutachtenportalservice API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentPropertiesDto } from './document-properties-dto';


export interface DocumentMetadataDto { 
    description?: string;
    filename: string;
    readonly filesize?: number;
    filetype: string;
    readonly createdOn?: string;
    readonly createdBy?: string;
    readonly changedOn?: string;
    readonly changedBy?: string;
    tags?: Array<string>;
    properties?: DocumentPropertiesDto;
}

