/**
 * Gutachtenportalservice API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentAccessDto } from './document-access-dto';
import { DocumentMetadataDto } from './document-metadata-dto';


export interface DokumentOhneDatenDto { 
    metadaten: DocumentMetadataDto;
    acl?: Array<DocumentAccessDto>;
    /**
     * UUID des erzeugten Dokumentes.
     */
    readonly documentId?: string;
}

