/**
 * Gutachtenportalservice API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GutachtenDto } from './gutachten-dto';
import { GutachtenstatusDto } from './gutachtenstatus-dto';
import { OrganisationDto } from './organisation-dto';
import { DokumentOhneDatenDto } from './dokument-ohne-daten-dto';
import { ProbandDto } from './proband-dto';
import { GutachterDto } from './gutachter-dto';


export interface GutachtenauftragDto { 
    /**
     * UUID of the created assessment.
     */
    readonly auftragsId: string;
    proband: ProbandDto;
    gutachter: GutachterDto;
    readonly auftraggeber: OrganisationDto;
    readonly kennzeichen1?: string;
    readonly kennzeichen2?: string;
    gutachtenstatus: GutachtenstatusDto;
    readonly anhaenge?: Array<DokumentOhneDatenDto>;
    gutachten?: GutachtenDto;
    /**
     * Wann wurde der Auftrag in rvSMD angelegt.
     */
    readonly auftragsdatum: string;
    /**
     * Wann ist der Auftrag in rvGutachten angekommen.
     */
    readonly eingangsdatum: string;
    /**
     * Wann sind alle Dokumente zu einem Auftrag in rvGutachten einsehbar
     */
    readonly bereitstellungsdatum?: string;
    /**
     * Zu wann wird der Proband einbestellt
     */
    einbestelldatum?: string;
}

