/**
 * Gutachtenportalservice API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GutachtenauftragDto } from './gutachtenauftrag-dto';


export interface GutachtenauftragListDto { 
    /**
     * Gesamtanzahlanzahl der Aufträge
     */
    anzahl: number;
    /**
     * Offset-Parameter der Anfrage
     */
    offset: number;
    /**
     * Anzahl der Aufträge in der Ergebnismenge
     */
    limit: number;
    auftraege: Array<GutachtenauftragDto>;
}

