/**
 * Gutachtenportalservice API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Status des Gutachtenauftrages
 */
export interface GutachtenstatusDto { 
    /**
     * 
     */
    status: GutachtenstatusDto.StatusEnum;
    /**
     * Timestamp der Statusänderung (UTC)
     */
    readonly changedOn?: string;
}
export namespace GutachtenstatusDto {
    export const StatusEnum = {
        Neu: 'neu',
        Einbestellt: 'einbestellt',
        InBearbeitung: 'in_bearbeitung',
        Abgeschlossen: 'abgeschlossen',
        Storniert: 'storniert'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


