/**
 * Gutachtenportalservice API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GutachtenDto { 
    /**
     * UUID of the created assessment.
     */
    readonly auftragsId?: string;
    /**
     * Gutachtenformular
     */
    s0080?: object;
    readonly anhaenge?: Array<string>;
}

