/**
 * Gutachtenportalservice API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A JSONPatch document as defined by RFC 6902
 */
export interface PatchDocument { 
    /**
     * The operation to be performed
     */
    op: PatchDocument.OpEnum;
    /**
     * A JSON-Pointer
     */
    path: string;
    /**
     * The value to be used within the operations.
     */
    value?: object;
    /**
     * A string containing a JSON Pointer value.
     */
    from?: string;
}
export namespace PatchDocument {
    export const OpEnum = {
        Add: 'add',
        Remove: 'remove',
        Replace: 'replace',
        Move: 'move',
        Copy: 'copy',
        Test: 'test'
    } as const;
    export type OpEnum = typeof OpEnum[keyof typeof OpEnum];
}


