/**
 * Gutachtenportalservice API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { DokumentListDto } from '../model/dokument-list-dto';
// @ts-ignore
import { ErrorResponseDto } from '../model/error-response-dto';
// @ts-ignore
import { GutachtenauftragDto } from '../model/gutachtenauftrag-dto';
// @ts-ignore
import { GutachtenauftragListDto } from '../model/gutachtenauftrag-list-dto';
// @ts-ignore
import { PatchRequest } from '../model/patch-request';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { GutachtenportalConfiguration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class GutachtenauftragApiClient extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: GutachtenportalConfiguration) {
        super(basePath, configuration);
    }

    /**
     * Gibt Gutachtenaufträge in einer Liste zurück
     * @param xOrgId Organisations-Id des Gutachters und des Gutachtermitarbeiters - Wird durch API-Gateway gesetzt
     * @param xUserId User-Id des Gutachters bzw. des Gutachtermitarbeiters - Wird durch API-Gateway gesetzt
     * @param xGutachterId UserId des dem User zugeordneten Gutachters - Wird durch API-Gateway gesetzt
     * @param offset The number of items to skip before starting to collect the result set.
     * @param limit Number of Items to return
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getGutachtenauftraege(xOrgId: string, xUserId: string, xGutachterId: string, offset?: number, limit?: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<GutachtenauftragListDto>;
    public getGutachtenauftraege(xOrgId: string, xUserId: string, xGutachterId: string, offset?: number, limit?: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GutachtenauftragListDto>>;
    public getGutachtenauftraege(xOrgId: string, xUserId: string, xGutachterId: string, offset?: number, limit?: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GutachtenauftragListDto>>;
    public getGutachtenauftraege(xOrgId: string, xUserId: string, xGutachterId: string, offset?: number, limit?: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling getGutachtenauftraege.');
        }
        if (xUserId === null || xUserId === undefined) {
            throw new Error('Required parameter xUserId was null or undefined when calling getGutachtenauftraege.');
        }
        if (xGutachterId === null || xGutachterId === undefined) {
            throw new Error('Required parameter xGutachterId was null or undefined when calling getGutachtenauftraege.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>offset, 'offset');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>limit, 'limit');

        let localVarHeaders = this.defaultHeaders;
        if (xOrgId !== undefined && xOrgId !== null) {
            localVarHeaders = localVarHeaders.set('X-OrgId', String(xOrgId));
        }
        if (xUserId !== undefined && xUserId !== null) {
            localVarHeaders = localVarHeaders.set('X-UserId', String(xUserId));
        }
        if (xGutachterId !== undefined && xGutachterId !== null) {
            localVarHeaders = localVarHeaders.set('X-GutachterId', String(xGutachterId));
        }

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/gutachtenauftraege`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GutachtenauftragListDto>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Gibt die Anhänge eines Gutachtenauftrags zurück
     * @param id ID des Gutachtenauftrages
     * @param xOrgId Organisations-Id des Gutachters und des Gutachtermitarbeiters - Wird durch API-Gateway gesetzt
     * @param xUserId User-Id des Gutachters bzw. des Gutachtermitarbeiters - Wird durch API-Gateway gesetzt
     * @param xGutachterId UserId des dem User zugeordneten Gutachters - Wird durch API-Gateway gesetzt
     * @param offset The number of items to skip before starting to collect the result set.
     * @param limit Number of Items to return
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getGutachtenauftragAnhaenge(id: string, xOrgId: string, xUserId: string, xGutachterId: string, offset?: number, limit?: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<DokumentListDto>;
    public getGutachtenauftragAnhaenge(id: string, xOrgId: string, xUserId: string, xGutachterId: string, offset?: number, limit?: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<DokumentListDto>>;
    public getGutachtenauftragAnhaenge(id: string, xOrgId: string, xUserId: string, xGutachterId: string, offset?: number, limit?: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<DokumentListDto>>;
    public getGutachtenauftragAnhaenge(id: string, xOrgId: string, xUserId: string, xGutachterId: string, offset?: number, limit?: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getGutachtenauftragAnhaenge.');
        }
        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling getGutachtenauftragAnhaenge.');
        }
        if (xUserId === null || xUserId === undefined) {
            throw new Error('Required parameter xUserId was null or undefined when calling getGutachtenauftragAnhaenge.');
        }
        if (xGutachterId === null || xGutachterId === undefined) {
            throw new Error('Required parameter xGutachterId was null or undefined when calling getGutachtenauftragAnhaenge.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>offset, 'offset');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>limit, 'limit');

        let localVarHeaders = this.defaultHeaders;
        if (xOrgId !== undefined && xOrgId !== null) {
            localVarHeaders = localVarHeaders.set('X-OrgId', String(xOrgId));
        }
        if (xUserId !== undefined && xUserId !== null) {
            localVarHeaders = localVarHeaders.set('X-UserId', String(xUserId));
        }
        if (xGutachterId !== undefined && xGutachterId !== null) {
            localVarHeaders = localVarHeaders.set('X-GutachterId', String(xGutachterId));
        }

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/gutachtenauftraege/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid"})}/anhaenge`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<DokumentListDto>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Gibt einen Gutachtenauftrag zurück
     * @param id ID des Gutachtenauftrages
     * @param xOrgId Organisations-Id des Gutachters und des Gutachtermitarbeiters - Wird durch API-Gateway gesetzt
     * @param xUserId User-Id des Gutachters bzw. des Gutachtermitarbeiters - Wird durch API-Gateway gesetzt
     * @param xGutachterId UserId des dem User zugeordneten Gutachters - Wird durch API-Gateway gesetzt
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getGutachtenauftragById(id: string, xOrgId: string, xUserId: string, xGutachterId: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<GutachtenauftragDto>;
    public getGutachtenauftragById(id: string, xOrgId: string, xUserId: string, xGutachterId: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GutachtenauftragDto>>;
    public getGutachtenauftragById(id: string, xOrgId: string, xUserId: string, xGutachterId: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GutachtenauftragDto>>;
    public getGutachtenauftragById(id: string, xOrgId: string, xUserId: string, xGutachterId: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getGutachtenauftragById.');
        }
        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling getGutachtenauftragById.');
        }
        if (xUserId === null || xUserId === undefined) {
            throw new Error('Required parameter xUserId was null or undefined when calling getGutachtenauftragById.');
        }
        if (xGutachterId === null || xGutachterId === undefined) {
            throw new Error('Required parameter xGutachterId was null or undefined when calling getGutachtenauftragById.');
        }

        let localVarHeaders = this.defaultHeaders;
        if (xOrgId !== undefined && xOrgId !== null) {
            localVarHeaders = localVarHeaders.set('X-OrgId', String(xOrgId));
        }
        if (xUserId !== undefined && xUserId !== null) {
            localVarHeaders = localVarHeaders.set('X-UserId', String(xUserId));
        }
        if (xGutachterId !== undefined && xGutachterId !== null) {
            localVarHeaders = localVarHeaders.set('X-GutachterId', String(xGutachterId));
        }

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/gutachtenauftraege/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid"})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GutachtenauftragDto>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Aktualisiert die aktualisierbaren Daten zu einem Auftrag
     * @param id ID des Gutachtenauftrages
     * @param xOrgId Organisations-Id des Gutachters und des Gutachtermitarbeiters - Wird durch API-Gateway gesetzt
     * @param xUserId User-Id des Gutachters bzw. des Gutachtermitarbeiters - Wird durch API-Gateway gesetzt
     * @param xGutachterId UserId des dem User zugeordneten Gutachters - Wird durch API-Gateway gesetzt
     * @param patchRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public patchGutachtenauftrag(id: string, xOrgId: string, xUserId: string, xGutachterId: string, patchRequest: PatchRequest, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any>;
    public patchGutachtenauftrag(id: string, xOrgId: string, xUserId: string, xGutachterId: string, patchRequest: PatchRequest, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<any>>;
    public patchGutachtenauftrag(id: string, xOrgId: string, xUserId: string, xGutachterId: string, patchRequest: PatchRequest, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<any>>;
    public patchGutachtenauftrag(id: string, xOrgId: string, xUserId: string, xGutachterId: string, patchRequest: PatchRequest, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling patchGutachtenauftrag.');
        }
        if (xOrgId === null || xOrgId === undefined) {
            throw new Error('Required parameter xOrgId was null or undefined when calling patchGutachtenauftrag.');
        }
        if (xUserId === null || xUserId === undefined) {
            throw new Error('Required parameter xUserId was null or undefined when calling patchGutachtenauftrag.');
        }
        if (xGutachterId === null || xGutachterId === undefined) {
            throw new Error('Required parameter xGutachterId was null or undefined when calling patchGutachtenauftrag.');
        }
        if (patchRequest === null || patchRequest === undefined) {
            throw new Error('Required parameter patchRequest was null or undefined when calling patchGutachtenauftrag.');
        }

        let localVarHeaders = this.defaultHeaders;
        if (xOrgId !== undefined && xOrgId !== null) {
            localVarHeaders = localVarHeaders.set('X-OrgId', String(xOrgId));
        }
        if (xUserId !== undefined && xUserId !== null) {
            localVarHeaders = localVarHeaders.set('X-UserId', String(xUserId));
        }
        if (xGutachterId !== undefined && xGutachterId !== null) {
            localVarHeaders = localVarHeaders.set('X-GutachterId', String(xGutachterId));
        }

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/gutachtenauftraege/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: "uuid"})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<any>('patch', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: patchRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
