/**
 * UserService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Adressinformationen des Nutzers oder der Organisation
 */
export interface AddresseDto { 
    strasse?: string;
    hausnummer?: string;
    plz?: string;
    ort?: string;
    addresszusatz?: string;
    postfach?: string;
    land?: string;
}

