/**
 * UserService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LastLoginDto } from './last-login-dto';
import { GutachtermitarbeiterDto } from './gutachtermitarbeiter-dto';
import { AdminDto } from './admin-dto';
import { OrganisationDto } from './organisation-dto';
import { AddresseDto } from './addresse-dto';
import { EinstellungDto } from './einstellung-dto';
import { Rollen } from './rollen';
import { KontaktDto } from './kontakt-dto';
import { GutachterDto } from './gutachter-dto';
import { RvSmdIdDto } from './rv-smd-id-dto';
import { NameDto } from './name-dto';


/**
 * In Abhaengigkeit des Header-Parameters X-rolle wird bei Wert \'gutachter\' GutachterDto, bei Wert \'gutachtermitarbeiter\' GutachtermitarbeiterDto und bei Wert \'admin\' AdminDto zurueckgegeben.
 */
/**
 * @type GetUserInfo200Response
 * In Abhaengigkeit des Header-Parameters X-rolle wird bei Wert \'gutachter\' GutachterDto, bei Wert \'gutachtermitarbeiter\' GutachtermitarbeiterDto und bei Wert \'admin\' AdminDto zurueckgegeben.
 * @export
 */
export type GetUserInfo200Response = AdminDto | GutachterDto | GutachtermitarbeiterDto;

