/**
 * UserService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LastLoginDto } from './last-login-dto';
import { OrganisationDto } from './organisation-dto';
import { AddresseDto } from './addresse-dto';
import { EinstellungDto } from './einstellung-dto';
import { Rollen } from './rollen';
import { KontaktDto } from './kontakt-dto';
import { NameDto } from './name-dto';


/**
 * Daten des Nutzers vom Profiltyp Gutachtermitarbeiter
 */
export interface GutachtermitarbeiterDto { 
    /**
     * ID des Nutzers
     */
    readonly userId: string;
    organisation: OrganisationDto;
    name: NameDto;
    readonly rollen: Rollen;
    adressen: Array<AddresseDto>;
    kontakt: Array<KontaktDto>;
    readonly letzterLogin?: LastLoginDto;
    /**
     * Aktivierungsstatus des Nutzers
     */
    readonly nutzerstatus: GutachtermitarbeiterDto.NutzerstatusEnum;
    /**
     * Typ des Nutzerprofils. Zulässige Werte sind \'gutachter\', \'gutachtermitarbeiter\' und \'admin\'.
     */
    readonly profiltyp: GutachtermitarbeiterDto.ProfiltypEnum;
    readonly settings?: EinstellungDto;
    /**
     * Link zum Avatar oder Default-Avatar
     */
    readonly avatar?: string;
    /**
     * Zeitstempel der Sperrung
     */
    gesperrtSeit?: string;
}
export namespace GutachtermitarbeiterDto {
    export const NutzerstatusEnum = {
        Angelegt: 'angelegt',
        EmailsVerifiziert: 'emails_verifiziert',
        Aktiviert: 'aktiviert',
        Gesperrt: 'gesperrt'
    } as const;
    export type NutzerstatusEnum = typeof NutzerstatusEnum[keyof typeof NutzerstatusEnum];
    export const ProfiltypEnum = {
        Gutachter: 'gutachter',
        Gutachtermitarbeiter: 'gutachtermitarbeiter',
        Admin: 'admin'
    } as const;
    export type ProfiltypEnum = typeof ProfiltypEnum[keyof typeof ProfiltypEnum];
}


