/**
 * UserService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Kontaktinformationen des Nutzers oder der Organisation
 */
export interface KontaktDto { 
    /**
     * Typ der Kontaktinformation (Email oder Telefon)
     */
    typ?: KontaktDto.TypEnum;
    /**
     * Wert der Kontaktinformation (Emailadresse oder Telefonnummer)
     */
    wert?: string;
    /**
     * Anmerkung zur Kontaktinformation
     */
    anmerkung?: string;
}
export namespace KontaktDto {
    export const TypEnum = {
        Email: 'Email',
        Telefon: 'Telefon'
    } as const;
    export type TypEnum = typeof TypEnum[keyof typeof TypEnum];
}


