/**
 * UserService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Idendifikatisdaten des Nutzers in rvSMD
 */
export interface RvSmdIdDto { 
    /**
     * Identifikation des Kostenträgers (Abkürzung für Kontoführende Versicherungsanstalt)
     */
    ktan: string;
    /**
     * ID des Nutzers in rvSMD
     */
    gutachterId: string;
}

